// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: room_events.proto
// Protobuf Java Version: 4.33.2

@com.google.protobuf.Generated
public final class RoomEventsProto extends com.google.protobuf.GeneratedFile {
  private RoomEventsProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "RoomEventsProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RoomEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProblemSolved_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProblemSolved_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomStarted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RoomStarted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomReadyFailed_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RoomReadyFailed_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021room_events.proto\"\331\001\n\tRoomEvent\022\027\n\007roo" +
      "m_id\030\001 \001(\003R\006roomId\0227\n\016problem_solved\030\002 \001" +
      "(\0132\016.ProblemSolvedH\000R\rproblemSolved\0221\n\014r" +
      "oom_started\030\003 \001(\0132\014.RoomStartedH\000R\013roomS" +
      "tarted\022>\n\021room_ready_failed\030\004 \001(\0132\020.Room" +
      "ReadyFailedH\000R\017roomReadyFailedB\007\n\005event\"" +
      "J\n\rProblemSolved\022\035\n\nproblem_id\030\001 \001(\tR\tpr" +
      "oblemId\022\032\n\010username\030\002 \001(\tR\010username\"\r\n\013R" +
      "oomStarted\"+\n\017RoomReadyFailed\022\030\n\007message" +
      "\030\001 \001(\tR\007messageB\023B\017RoomEventsProtoP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RoomEvent_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_RoomEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RoomEvent_descriptor,
        new java.lang.String[] { "RoomId", "ProblemSolved", "RoomStarted", "RoomReadyFailed", "Event", });
    internal_static_ProblemSolved_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_ProblemSolved_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProblemSolved_descriptor,
        new java.lang.String[] { "ProblemId", "Username", });
    internal_static_RoomStarted_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_RoomStarted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RoomStarted_descriptor,
        new java.lang.String[] { });
    internal_static_RoomReadyFailed_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_RoomReadyFailed_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RoomReadyFailed_descriptor,
        new java.lang.String[] { "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
