// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: room_events.proto
// Protobuf Java Version: 4.33.2

@com.google.protobuf.Generated
public interface RoomReadyFailedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomReadyFailed)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1 [json_name = "message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
