// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: room_events.proto
// Protobuf Java Version: 4.33.2

/**
 * Protobuf type {@code RoomEvent}
 */
@com.google.protobuf.Generated
public final class RoomEvent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:RoomEvent)
    RoomEventOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "RoomEvent");
  }
  // Use RoomEvent.newBuilder() to construct.
  private RoomEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RoomEvent() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RoomEventsProto.internal_static_RoomEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RoomEventsProto.internal_static_RoomEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RoomEvent.class, RoomEvent.Builder.class);
  }

  private int eventCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object event_;
  public enum EventCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    PROBLEM_SOLVED(2),
    ROOM_STARTED(3),
    ROOM_READY_FAILED(4),
    EVENT_NOT_SET(0);
    private final int value;
    private EventCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventCase valueOf(int value) {
      return forNumber(value);
    }

    public static EventCase forNumber(int value) {
      switch (value) {
        case 2: return PROBLEM_SOLVED;
        case 3: return ROOM_STARTED;
        case 4: return ROOM_READY_FAILED;
        case 0: return EVENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public EventCase
  getEventCase() {
    return EventCase.forNumber(
        eventCase_);
  }

  public static final int ROOM_ID_FIELD_NUMBER = 1;
  private long roomId_ = 0L;
  /**
   * <code>int64 room_id = 1 [json_name = "roomId"];</code>
   * @return The roomId.
   */
  @java.lang.Override
  public long getRoomId() {
    return roomId_;
  }

  public static final int PROBLEM_SOLVED_FIELD_NUMBER = 2;
  /**
   * <code>.ProblemSolved problem_solved = 2 [json_name = "problemSolved"];</code>
   * @return Whether the problemSolved field is set.
   */
  @java.lang.Override
  public boolean hasProblemSolved() {
    return eventCase_ == 2;
  }
  /**
   * <code>.ProblemSolved problem_solved = 2 [json_name = "problemSolved"];</code>
   * @return The problemSolved.
   */
  @java.lang.Override
  public ProblemSolved getProblemSolved() {
    if (eventCase_ == 2) {
       return (ProblemSolved) event_;
    }
    return ProblemSolved.getDefaultInstance();
  }
  /**
   * <code>.ProblemSolved problem_solved = 2 [json_name = "problemSolved"];</code>
   */
  @java.lang.Override
  public ProblemSolvedOrBuilder getProblemSolvedOrBuilder() {
    if (eventCase_ == 2) {
       return (ProblemSolved) event_;
    }
    return ProblemSolved.getDefaultInstance();
  }

  public static final int ROOM_STARTED_FIELD_NUMBER = 3;
  /**
   * <code>.RoomStarted room_started = 3 [json_name = "roomStarted"];</code>
   * @return Whether the roomStarted field is set.
   */
  @java.lang.Override
  public boolean hasRoomStarted() {
    return eventCase_ == 3;
  }
  /**
   * <code>.RoomStarted room_started = 3 [json_name = "roomStarted"];</code>
   * @return The roomStarted.
   */
  @java.lang.Override
  public RoomStarted getRoomStarted() {
    if (eventCase_ == 3) {
       return (RoomStarted) event_;
    }
    return RoomStarted.getDefaultInstance();
  }
  /**
   * <code>.RoomStarted room_started = 3 [json_name = "roomStarted"];</code>
   */
  @java.lang.Override
  public RoomStartedOrBuilder getRoomStartedOrBuilder() {
    if (eventCase_ == 3) {
       return (RoomStarted) event_;
    }
    return RoomStarted.getDefaultInstance();
  }

  public static final int ROOM_READY_FAILED_FIELD_NUMBER = 4;
  /**
   * <code>.RoomReadyFailed room_ready_failed = 4 [json_name = "roomReadyFailed"];</code>
   * @return Whether the roomReadyFailed field is set.
   */
  @java.lang.Override
  public boolean hasRoomReadyFailed() {
    return eventCase_ == 4;
  }
  /**
   * <code>.RoomReadyFailed room_ready_failed = 4 [json_name = "roomReadyFailed"];</code>
   * @return The roomReadyFailed.
   */
  @java.lang.Override
  public RoomReadyFailed getRoomReadyFailed() {
    if (eventCase_ == 4) {
       return (RoomReadyFailed) event_;
    }
    return RoomReadyFailed.getDefaultInstance();
  }
  /**
   * <code>.RoomReadyFailed room_ready_failed = 4 [json_name = "roomReadyFailed"];</code>
   */
  @java.lang.Override
  public RoomReadyFailedOrBuilder getRoomReadyFailedOrBuilder() {
    if (eventCase_ == 4) {
       return (RoomReadyFailed) event_;
    }
    return RoomReadyFailed.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (roomId_ != 0L) {
      output.writeInt64(1, roomId_);
    }
    if (eventCase_ == 2) {
      output.writeMessage(2, (ProblemSolved) event_);
    }
    if (eventCase_ == 3) {
      output.writeMessage(3, (RoomStarted) event_);
    }
    if (eventCase_ == 4) {
      output.writeMessage(4, (RoomReadyFailed) event_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (roomId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, roomId_);
    }
    if (eventCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (ProblemSolved) event_);
    }
    if (eventCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (RoomStarted) event_);
    }
    if (eventCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (RoomReadyFailed) event_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RoomEvent)) {
      return super.equals(obj);
    }
    RoomEvent other = (RoomEvent) obj;

    if (getRoomId()
        != other.getRoomId()) return false;
    if (!getEventCase().equals(other.getEventCase())) return false;
    switch (eventCase_) {
      case 2:
        if (!getProblemSolved()
            .equals(other.getProblemSolved())) return false;
        break;
      case 3:
        if (!getRoomStarted()
            .equals(other.getRoomStarted())) return false;
        break;
      case 4:
        if (!getRoomReadyFailed()
            .equals(other.getRoomReadyFailed())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRoomId());
    switch (eventCase_) {
      case 2:
        hash = (37 * hash) + PROBLEM_SOLVED_FIELD_NUMBER;
        hash = (53 * hash) + getProblemSolved().hashCode();
        break;
      case 3:
        hash = (37 * hash) + ROOM_STARTED_FIELD_NUMBER;
        hash = (53 * hash) + getRoomStarted().hashCode();
        break;
      case 4:
        hash = (37 * hash) + ROOM_READY_FAILED_FIELD_NUMBER;
        hash = (53 * hash) + getRoomReadyFailed().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RoomEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RoomEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RoomEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RoomEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RoomEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RoomEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RoomEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static RoomEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static RoomEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static RoomEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RoomEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static RoomEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RoomEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RoomEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RoomEvent)
      RoomEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RoomEventsProto.internal_static_RoomEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RoomEventsProto.internal_static_RoomEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RoomEvent.class, RoomEvent.Builder.class);
    }

    // Construct using RoomEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      roomId_ = 0L;
      if (problemSolvedBuilder_ != null) {
        problemSolvedBuilder_.clear();
      }
      if (roomStartedBuilder_ != null) {
        roomStartedBuilder_.clear();
      }
      if (roomReadyFailedBuilder_ != null) {
        roomReadyFailedBuilder_.clear();
      }
      eventCase_ = 0;
      event_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RoomEventsProto.internal_static_RoomEvent_descriptor;
    }

    @java.lang.Override
    public RoomEvent getDefaultInstanceForType() {
      return RoomEvent.getDefaultInstance();
    }

    @java.lang.Override
    public RoomEvent build() {
      RoomEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public RoomEvent buildPartial() {
      RoomEvent result = new RoomEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(RoomEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.roomId_ = roomId_;
      }
    }

    private void buildPartialOneofs(RoomEvent result) {
      result.eventCase_ = eventCase_;
      result.event_ = this.event_;
      if (eventCase_ == 2 &&
          problemSolvedBuilder_ != null) {
        result.event_ = problemSolvedBuilder_.build();
      }
      if (eventCase_ == 3 &&
          roomStartedBuilder_ != null) {
        result.event_ = roomStartedBuilder_.build();
      }
      if (eventCase_ == 4 &&
          roomReadyFailedBuilder_ != null) {
        result.event_ = roomReadyFailedBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RoomEvent) {
        return mergeFrom((RoomEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RoomEvent other) {
      if (other == RoomEvent.getDefaultInstance()) return this;
      if (other.getRoomId() != 0L) {
        setRoomId(other.getRoomId());
      }
      switch (other.getEventCase()) {
        case PROBLEM_SOLVED: {
          mergeProblemSolved(other.getProblemSolved());
          break;
        }
        case ROOM_STARTED: {
          mergeRoomStarted(other.getRoomStarted());
          break;
        }
        case ROOM_READY_FAILED: {
          mergeRoomReadyFailed(other.getRoomReadyFailed());
          break;
        }
        case EVENT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              roomId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  internalGetProblemSolvedFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetRoomStartedFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetRoomReadyFailedFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 4;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int eventCase_ = 0;
    private java.lang.Object event_;
    public EventCase
        getEventCase() {
      return EventCase.forNumber(
          eventCase_);
    }

    public Builder clearEvent() {
      eventCase_ = 0;
      event_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private long roomId_ ;
    /**
     * <code>int64 room_id = 1 [json_name = "roomId"];</code>
     * @return The roomId.
     */
    @java.lang.Override
    public long getRoomId() {
      return roomId_;
    }
    /**
     * <code>int64 room_id = 1 [json_name = "roomId"];</code>
     * @param value The roomId to set.
     * @return This builder for chaining.
     */
    public Builder setRoomId(long value) {

      roomId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 room_id = 1 [json_name = "roomId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      roomId_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        ProblemSolved, ProblemSolved.Builder, ProblemSolvedOrBuilder> problemSolvedBuilder_;
    /**
     * <code>.ProblemSolved problem_solved = 2 [json_name = "problemSolved"];</code>
     * @return Whether the problemSolved field is set.
     */
    @java.lang.Override
    public boolean hasProblemSolved() {
      return eventCase_ == 2;
    }
    /**
     * <code>.ProblemSolved problem_solved = 2 [json_name = "problemSolved"];</code>
     * @return The problemSolved.
     */
    @java.lang.Override
    public ProblemSolved getProblemSolved() {
      if (problemSolvedBuilder_ == null) {
        if (eventCase_ == 2) {
          return (ProblemSolved) event_;
        }
        return ProblemSolved.getDefaultInstance();
      } else {
        if (eventCase_ == 2) {
          return problemSolvedBuilder_.getMessage();
        }
        return ProblemSolved.getDefaultInstance();
      }
    }
    /**
     * <code>.ProblemSolved problem_solved = 2 [json_name = "problemSolved"];</code>
     */
    public Builder setProblemSolved(ProblemSolved value) {
      if (problemSolvedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        problemSolvedBuilder_.setMessage(value);
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.ProblemSolved problem_solved = 2 [json_name = "problemSolved"];</code>
     */
    public Builder setProblemSolved(
        ProblemSolved.Builder builderForValue) {
      if (problemSolvedBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        problemSolvedBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.ProblemSolved problem_solved = 2 [json_name = "problemSolved"];</code>
     */
    public Builder mergeProblemSolved(ProblemSolved value) {
      if (problemSolvedBuilder_ == null) {
        if (eventCase_ == 2 &&
            event_ != ProblemSolved.getDefaultInstance()) {
          event_ = ProblemSolved.newBuilder((ProblemSolved) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 2) {
          problemSolvedBuilder_.mergeFrom(value);
        } else {
          problemSolvedBuilder_.setMessage(value);
        }
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.ProblemSolved problem_solved = 2 [json_name = "problemSolved"];</code>
     */
    public Builder clearProblemSolved() {
      if (problemSolvedBuilder_ == null) {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
        }
        problemSolvedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ProblemSolved problem_solved = 2 [json_name = "problemSolved"];</code>
     */
    public ProblemSolved.Builder getProblemSolvedBuilder() {
      return internalGetProblemSolvedFieldBuilder().getBuilder();
    }
    /**
     * <code>.ProblemSolved problem_solved = 2 [json_name = "problemSolved"];</code>
     */
    @java.lang.Override
    public ProblemSolvedOrBuilder getProblemSolvedOrBuilder() {
      if ((eventCase_ == 2) && (problemSolvedBuilder_ != null)) {
        return problemSolvedBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 2) {
          return (ProblemSolved) event_;
        }
        return ProblemSolved.getDefaultInstance();
      }
    }
    /**
     * <code>.ProblemSolved problem_solved = 2 [json_name = "problemSolved"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        ProblemSolved, ProblemSolved.Builder, ProblemSolvedOrBuilder> 
        internalGetProblemSolvedFieldBuilder() {
      if (problemSolvedBuilder_ == null) {
        if (!(eventCase_ == 2)) {
          event_ = ProblemSolved.getDefaultInstance();
        }
        problemSolvedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            ProblemSolved, ProblemSolved.Builder, ProblemSolvedOrBuilder>(
                (ProblemSolved) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 2;
      onChanged();
      return problemSolvedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        RoomStarted, RoomStarted.Builder, RoomStartedOrBuilder> roomStartedBuilder_;
    /**
     * <code>.RoomStarted room_started = 3 [json_name = "roomStarted"];</code>
     * @return Whether the roomStarted field is set.
     */
    @java.lang.Override
    public boolean hasRoomStarted() {
      return eventCase_ == 3;
    }
    /**
     * <code>.RoomStarted room_started = 3 [json_name = "roomStarted"];</code>
     * @return The roomStarted.
     */
    @java.lang.Override
    public RoomStarted getRoomStarted() {
      if (roomStartedBuilder_ == null) {
        if (eventCase_ == 3) {
          return (RoomStarted) event_;
        }
        return RoomStarted.getDefaultInstance();
      } else {
        if (eventCase_ == 3) {
          return roomStartedBuilder_.getMessage();
        }
        return RoomStarted.getDefaultInstance();
      }
    }
    /**
     * <code>.RoomStarted room_started = 3 [json_name = "roomStarted"];</code>
     */
    public Builder setRoomStarted(RoomStarted value) {
      if (roomStartedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        roomStartedBuilder_.setMessage(value);
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>.RoomStarted room_started = 3 [json_name = "roomStarted"];</code>
     */
    public Builder setRoomStarted(
        RoomStarted.Builder builderForValue) {
      if (roomStartedBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        roomStartedBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>.RoomStarted room_started = 3 [json_name = "roomStarted"];</code>
     */
    public Builder mergeRoomStarted(RoomStarted value) {
      if (roomStartedBuilder_ == null) {
        if (eventCase_ == 3 &&
            event_ != RoomStarted.getDefaultInstance()) {
          event_ = RoomStarted.newBuilder((RoomStarted) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 3) {
          roomStartedBuilder_.mergeFrom(value);
        } else {
          roomStartedBuilder_.setMessage(value);
        }
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>.RoomStarted room_started = 3 [json_name = "roomStarted"];</code>
     */
    public Builder clearRoomStarted() {
      if (roomStartedBuilder_ == null) {
        if (eventCase_ == 3) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 3) {
          eventCase_ = 0;
          event_ = null;
        }
        roomStartedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.RoomStarted room_started = 3 [json_name = "roomStarted"];</code>
     */
    public RoomStarted.Builder getRoomStartedBuilder() {
      return internalGetRoomStartedFieldBuilder().getBuilder();
    }
    /**
     * <code>.RoomStarted room_started = 3 [json_name = "roomStarted"];</code>
     */
    @java.lang.Override
    public RoomStartedOrBuilder getRoomStartedOrBuilder() {
      if ((eventCase_ == 3) && (roomStartedBuilder_ != null)) {
        return roomStartedBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 3) {
          return (RoomStarted) event_;
        }
        return RoomStarted.getDefaultInstance();
      }
    }
    /**
     * <code>.RoomStarted room_started = 3 [json_name = "roomStarted"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        RoomStarted, RoomStarted.Builder, RoomStartedOrBuilder> 
        internalGetRoomStartedFieldBuilder() {
      if (roomStartedBuilder_ == null) {
        if (!(eventCase_ == 3)) {
          event_ = RoomStarted.getDefaultInstance();
        }
        roomStartedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            RoomStarted, RoomStarted.Builder, RoomStartedOrBuilder>(
                (RoomStarted) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 3;
      onChanged();
      return roomStartedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        RoomReadyFailed, RoomReadyFailed.Builder, RoomReadyFailedOrBuilder> roomReadyFailedBuilder_;
    /**
     * <code>.RoomReadyFailed room_ready_failed = 4 [json_name = "roomReadyFailed"];</code>
     * @return Whether the roomReadyFailed field is set.
     */
    @java.lang.Override
    public boolean hasRoomReadyFailed() {
      return eventCase_ == 4;
    }
    /**
     * <code>.RoomReadyFailed room_ready_failed = 4 [json_name = "roomReadyFailed"];</code>
     * @return The roomReadyFailed.
     */
    @java.lang.Override
    public RoomReadyFailed getRoomReadyFailed() {
      if (roomReadyFailedBuilder_ == null) {
        if (eventCase_ == 4) {
          return (RoomReadyFailed) event_;
        }
        return RoomReadyFailed.getDefaultInstance();
      } else {
        if (eventCase_ == 4) {
          return roomReadyFailedBuilder_.getMessage();
        }
        return RoomReadyFailed.getDefaultInstance();
      }
    }
    /**
     * <code>.RoomReadyFailed room_ready_failed = 4 [json_name = "roomReadyFailed"];</code>
     */
    public Builder setRoomReadyFailed(RoomReadyFailed value) {
      if (roomReadyFailedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        roomReadyFailedBuilder_.setMessage(value);
      }
      eventCase_ = 4;
      return this;
    }
    /**
     * <code>.RoomReadyFailed room_ready_failed = 4 [json_name = "roomReadyFailed"];</code>
     */
    public Builder setRoomReadyFailed(
        RoomReadyFailed.Builder builderForValue) {
      if (roomReadyFailedBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        roomReadyFailedBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 4;
      return this;
    }
    /**
     * <code>.RoomReadyFailed room_ready_failed = 4 [json_name = "roomReadyFailed"];</code>
     */
    public Builder mergeRoomReadyFailed(RoomReadyFailed value) {
      if (roomReadyFailedBuilder_ == null) {
        if (eventCase_ == 4 &&
            event_ != RoomReadyFailed.getDefaultInstance()) {
          event_ = RoomReadyFailed.newBuilder((RoomReadyFailed) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 4) {
          roomReadyFailedBuilder_.mergeFrom(value);
        } else {
          roomReadyFailedBuilder_.setMessage(value);
        }
      }
      eventCase_ = 4;
      return this;
    }
    /**
     * <code>.RoomReadyFailed room_ready_failed = 4 [json_name = "roomReadyFailed"];</code>
     */
    public Builder clearRoomReadyFailed() {
      if (roomReadyFailedBuilder_ == null) {
        if (eventCase_ == 4) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 4) {
          eventCase_ = 0;
          event_ = null;
        }
        roomReadyFailedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.RoomReadyFailed room_ready_failed = 4 [json_name = "roomReadyFailed"];</code>
     */
    public RoomReadyFailed.Builder getRoomReadyFailedBuilder() {
      return internalGetRoomReadyFailedFieldBuilder().getBuilder();
    }
    /**
     * <code>.RoomReadyFailed room_ready_failed = 4 [json_name = "roomReadyFailed"];</code>
     */
    @java.lang.Override
    public RoomReadyFailedOrBuilder getRoomReadyFailedOrBuilder() {
      if ((eventCase_ == 4) && (roomReadyFailedBuilder_ != null)) {
        return roomReadyFailedBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 4) {
          return (RoomReadyFailed) event_;
        }
        return RoomReadyFailed.getDefaultInstance();
      }
    }
    /**
     * <code>.RoomReadyFailed room_ready_failed = 4 [json_name = "roomReadyFailed"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        RoomReadyFailed, RoomReadyFailed.Builder, RoomReadyFailedOrBuilder> 
        internalGetRoomReadyFailedFieldBuilder() {
      if (roomReadyFailedBuilder_ == null) {
        if (!(eventCase_ == 4)) {
          event_ = RoomReadyFailed.getDefaultInstance();
        }
        roomReadyFailedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            RoomReadyFailed, RoomReadyFailed.Builder, RoomReadyFailedOrBuilder>(
                (RoomReadyFailed) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 4;
      onChanged();
      return roomReadyFailedBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:RoomEvent)
  }

  // @@protoc_insertion_point(class_scope:RoomEvent)
  private static final RoomEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RoomEvent();
  }

  public static RoomEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RoomEvent>
      PARSER = new com.google.protobuf.AbstractParser<RoomEvent>() {
    @java.lang.Override
    public RoomEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RoomEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RoomEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public RoomEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

