// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: room_events.proto
// Protobuf Java Version: 4.33.2

@com.google.protobuf.Generated
public interface RoomStartedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomStarted)
    com.google.protobuf.MessageOrBuilder {
}
