// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: room_events.proto
// Protobuf Java Version: 4.33.2

@com.google.protobuf.Generated
public interface RoomEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 room_id = 1 [json_name = "roomId"];</code>
   * @return The roomId.
   */
  long getRoomId();

  /**
   * <code>.ProblemSolved problem_solved = 2 [json_name = "problemSolved"];</code>
   * @return Whether the problemSolved field is set.
   */
  boolean hasProblemSolved();
  /**
   * <code>.ProblemSolved problem_solved = 2 [json_name = "problemSolved"];</code>
   * @return The problemSolved.
   */
  ProblemSolved getProblemSolved();
  /**
   * <code>.ProblemSolved problem_solved = 2 [json_name = "problemSolved"];</code>
   */
  ProblemSolvedOrBuilder getProblemSolvedOrBuilder();

  /**
   * <code>.RoomStarted room_started = 3 [json_name = "roomStarted"];</code>
   * @return Whether the roomStarted field is set.
   */
  boolean hasRoomStarted();
  /**
   * <code>.RoomStarted room_started = 3 [json_name = "roomStarted"];</code>
   * @return The roomStarted.
   */
  RoomStarted getRoomStarted();
  /**
   * <code>.RoomStarted room_started = 3 [json_name = "roomStarted"];</code>
   */
  RoomStartedOrBuilder getRoomStartedOrBuilder();

  /**
   * <code>.RoomReadyFailed room_ready_failed = 4 [json_name = "roomReadyFailed"];</code>
   * @return Whether the roomReadyFailed field is set.
   */
  boolean hasRoomReadyFailed();
  /**
   * <code>.RoomReadyFailed room_ready_failed = 4 [json_name = "roomReadyFailed"];</code>
   * @return The roomReadyFailed.
   */
  RoomReadyFailed getRoomReadyFailed();
  /**
   * <code>.RoomReadyFailed room_ready_failed = 4 [json_name = "roomReadyFailed"];</code>
   */
  RoomReadyFailedOrBuilder getRoomReadyFailedOrBuilder();

  RoomEvent.EventCase getEventCase();
}
