// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: room_events.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
@kotlin.jvm.JvmName("-initializeproblemSolved")
public inline fun problemSolved(block: ProblemSolvedKt.Dsl.() -> kotlin.Unit): ProblemSolved =
  ProblemSolvedKt.Dsl._create(ProblemSolved.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ProblemSolved`
 */
public object ProblemSolvedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ProblemSolved.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ProblemSolved.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ProblemSolved = _builder.build()

    /**
     * `string problem_id = 1 [json_name = "problemId"];`
     */
    public var problemId: kotlin.String
      @kotlin.jvm.JvmName("getProblemId")
        get() = _builder.problemId
      @kotlin.jvm.JvmName("setProblemId")
        set(value) {
        _builder.problemId = value
      }
    /**
     * `string problem_id = 1 [json_name = "problemId"];`
     */
    public fun clearProblemId() {
      _builder.clearProblemId()
    }

    /**
     * `string username = 2 [json_name = "username"];`
     */
    public var username: kotlin.String
      @kotlin.jvm.JvmName("getUsername")
        get() = _builder.username
      @kotlin.jvm.JvmName("setUsername")
        set(value) {
        _builder.username = value
      }
    /**
     * `string username = 2 [json_name = "username"];`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ProblemSolved.copy(block: ProblemSolvedKt.Dsl.() -> kotlin.Unit): ProblemSolved =
  ProblemSolvedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

