// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: room_events.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
@kotlin.jvm.JvmName("-initializeroomStarted")
public inline fun roomStarted(block: RoomStartedKt.Dsl.() -> kotlin.Unit): RoomStarted =
  RoomStartedKt.Dsl._create(RoomStarted.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `RoomStarted`
 */
public object RoomStartedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: RoomStarted.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: RoomStarted.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): RoomStarted = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun RoomStarted.copy(block: RoomStartedKt.Dsl.() -> kotlin.Unit): RoomStarted =
  RoomStartedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

