// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: room_events.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
@kotlin.jvm.JvmName("-initializeroomReadyFailed")
public inline fun roomReadyFailed(block: RoomReadyFailedKt.Dsl.() -> kotlin.Unit): RoomReadyFailed =
  RoomReadyFailedKt.Dsl._create(RoomReadyFailed.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `RoomReadyFailed`
 */
public object RoomReadyFailedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: RoomReadyFailed.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: RoomReadyFailed.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): RoomReadyFailed = _builder.build()

    /**
     * `string message = 1 [json_name = "message"];`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * `string message = 1 [json_name = "message"];`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun RoomReadyFailed.copy(block: RoomReadyFailedKt.Dsl.() -> kotlin.Unit): RoomReadyFailed =
  RoomReadyFailedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

