// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: room_events.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
@kotlin.jvm.JvmName("-initializeroomEvent")
public inline fun roomEvent(block: RoomEventKt.Dsl.() -> kotlin.Unit): RoomEvent =
  RoomEventKt.Dsl._create(RoomEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `RoomEvent`
 */
public object RoomEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: RoomEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: RoomEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): RoomEvent = _builder.build()

    /**
     * `int64 room_id = 1 [json_name = "roomId"];`
     */
    public var roomId: kotlin.Long
      @kotlin.jvm.JvmName("getRoomId")
        get() = _builder.roomId
      @kotlin.jvm.JvmName("setRoomId")
        set(value) {
        _builder.roomId = value
      }
    /**
     * `int64 room_id = 1 [json_name = "roomId"];`
     */
    public fun clearRoomId() {
      _builder.clearRoomId()
    }

    /**
     * `.ProblemSolved problem_solved = 2 [json_name = "problemSolved"];`
     */
    public var problemSolved: ProblemSolved
      @kotlin.jvm.JvmName("getProblemSolved")
        get() = _builder.problemSolved
      @kotlin.jvm.JvmName("setProblemSolved")
        set(value) {
        _builder.problemSolved = value
      }
    /**
     * `.ProblemSolved problem_solved = 2 [json_name = "problemSolved"];`
     */
    public fun clearProblemSolved() {
      _builder.clearProblemSolved()
    }
    /**
     * `.ProblemSolved problem_solved = 2 [json_name = "problemSolved"];`
     * @return Whether the problemSolved field is set.
     */
    public fun hasProblemSolved(): kotlin.Boolean {
      return _builder.hasProblemSolved()
    }

    /**
     * `.RoomStarted room_started = 3 [json_name = "roomStarted"];`
     */
    public var roomStarted: RoomStarted
      @kotlin.jvm.JvmName("getRoomStarted")
        get() = _builder.roomStarted
      @kotlin.jvm.JvmName("setRoomStarted")
        set(value) {
        _builder.roomStarted = value
      }
    /**
     * `.RoomStarted room_started = 3 [json_name = "roomStarted"];`
     */
    public fun clearRoomStarted() {
      _builder.clearRoomStarted()
    }
    /**
     * `.RoomStarted room_started = 3 [json_name = "roomStarted"];`
     * @return Whether the roomStarted field is set.
     */
    public fun hasRoomStarted(): kotlin.Boolean {
      return _builder.hasRoomStarted()
    }

    /**
     * `.RoomReadyFailed room_ready_failed = 4 [json_name = "roomReadyFailed"];`
     */
    public var roomReadyFailed: RoomReadyFailed
      @kotlin.jvm.JvmName("getRoomReadyFailed")
        get() = _builder.roomReadyFailed
      @kotlin.jvm.JvmName("setRoomReadyFailed")
        set(value) {
        _builder.roomReadyFailed = value
      }
    /**
     * `.RoomReadyFailed room_ready_failed = 4 [json_name = "roomReadyFailed"];`
     */
    public fun clearRoomReadyFailed() {
      _builder.clearRoomReadyFailed()
    }
    /**
     * `.RoomReadyFailed room_ready_failed = 4 [json_name = "roomReadyFailed"];`
     * @return Whether the roomReadyFailed field is set.
     */
    public fun hasRoomReadyFailed(): kotlin.Boolean {
      return _builder.hasRoomReadyFailed()
    }
    public val eventCase: RoomEvent.EventCase
    @kotlin.jvm.JvmName("getEventCase")
      get() = _builder.getEventCase()

    public fun clearEvent() {
      _builder.clearEvent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun RoomEvent.copy(block: RoomEventKt.Dsl.() -> kotlin.Unit): RoomEvent =
  RoomEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val RoomEventOrBuilder.problemSolvedOrNull: ProblemSolved?
  get() = if (hasProblemSolved()) getProblemSolved() else null

public val RoomEventOrBuilder.roomStartedOrNull: RoomStarted?
  get() = if (hasRoomStarted()) getRoomStarted() else null

public val RoomEventOrBuilder.roomReadyFailedOrNull: RoomReadyFailed?
  get() = if (hasRoomReadyFailed()) getRoomReadyFailed() else null

