# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: room_events.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'room_events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11room_events.proto\"\xd9\x01\n\tRoomEvent\x12\x17\n\x07room_id\x18\x01 \x01(\x03R\x06roomId\x12\x37\n\x0eproblem_solved\x18\x02 \x01(\x0b\x32\x0e.ProblemSolvedH\x00R\rproblemSolved\x12\x31\n\x0croom_started\x18\x03 \x01(\x0b\x32\x0c.RoomStartedH\x00R\x0broomStarted\x12>\n\x11room_ready_failed\x18\x04 \x01(\x0b\x32\x10.RoomReadyFailedH\x00R\x0froomReadyFailedB\x07\n\x05\x65vent\"J\n\rProblemSolved\x12\x1d\n\nproblem_id\x18\x01 \x01(\tR\tproblemId\x12\x1a\n\x08username\x18\x02 \x01(\tR\x08username\"\r\n\x0bRoomStarted\"+\n\x0fRoomReadyFailed\x12\x18\n\x07message\x18\x01 \x01(\tR\x07messageB\x13\x42\x0fRoomEventsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'room_events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\017RoomEventsProtoP\001'
  _globals['_ROOMEVENT']._serialized_start=22
  _globals['_ROOMEVENT']._serialized_end=239
  _globals['_PROBLEMSOLVED']._serialized_start=241
  _globals['_PROBLEMSOLVED']._serialized_end=315
  _globals['_ROOMSTARTED']._serialized_start=317
  _globals['_ROOMSTARTED']._serialized_end=330
  _globals['_ROOMREADYFAILED']._serialized_start=332
  _globals['_ROOMREADYFAILED']._serialized_end=375
# @@protoc_insertion_point(module_scope)
